# Generated by Django 4.0.5 on 2022-07-26 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_ranked_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
