# Generated by Django 4.0.5 on 2022-07-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_player_avatar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='platform',
            field=models.CharField(choices=[('euw1', 'euw1'), ('br1', 'br1'), ('eun1', 'eun1'), ('jp1', 'jp1'), ('kr1', 'kr1'), ('la1', 'la1'), ('la2', 'la2'), ('oc1', 'oc1'), ('ru', 'ru'), ('tr1', 'tr1')], default='euw1', max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='region',
            field=models.CharField(choices=[('europe', 'europe'), ('americas', 'americas'), ('asia', 'asia')], default='europes', max_length=10),
        ),
    ]
