# Generated by Django 3.2 on 2021-04-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaguedata',
            old_name='league',
            new_name='rank',
        ),
        migrations.AddField(
            model_name='leaguedata',
            name='losses',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaguedata',
            name='wins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
