# Generated by Django 4.0.5 on 2022-07-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_player_last_ranked_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='lp',
            field=models.IntegerField(default=0, verbose_name='LP'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=24),
        ),
    ]
