# Generated by Django 4.0.5 on 2022-07-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_player_lp_alter_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar_id',
            field=models.CharField(default='', max_length=24),
        ),
    ]
