# Generated by Django 3.2 on 2021-04-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_miscdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscdata',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
