# Generated by Django 3.2 on 2021-04-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_miscdata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguedata',
            name='progress',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaguedata',
            name='winrate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
