# Generated by Django 3.2 on 2021-04-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20210423_1311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiscData',
        ),
    ]
