# Generated by Django 4.1 on 2022-08-13 09:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_challenge_ignore_unranked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ladder_Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_rank', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('NONE', 'NONE')], max_length=20)),
                ('starting_tier', models.CharField(choices=[('UNRANKED', 'UNRANKED'), ('IRON', 'IRON'), ('BRONZE', 'BRONZE'), ('SILVER', 'SILVER'), ('GOLD', 'GOLD'), ('PLATINUM', 'PLATINUM'), ('DIAMOND', 'DIAMOND'), ('MASTER', 'MASTER'), ('GRANDMASTER', 'GRANDMASTER'), ('CHALLENGER', 'CHALLENGER')], max_length=30)),
                ('starting_lp', models.IntegerField()),
                ('ignored', models.BooleanField(default=False)),
                ('progress', models.IntegerField(default=0)),
                ('progress_delta', models.IntegerField(default=0)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameModel(
            old_name='Challenge',
            new_name='Ladder',
        ),
        migrations.DeleteModel(
            name='Challenge_Player',
        ),
        migrations.AddField(
            model_name='ladder_player',
            name='ladder_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.ladder'),
        ),
        migrations.AddField(
            model_name='ladder_player',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.player'),
        ),
        migrations.AddIndex(
            model_name='ladder_player',
            index=models.Index(fields=['player_id', 'ladder_id'], name='tracker_lad_player__02b28c_idx'),
        ),
    ]
