# Generated by Django 3.2 on 2021-07-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_delete_miscdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('startingTier', models.CharField(max_length=30)),
                ('startingRank', models.CharField(max_length=10)),
                ('startingPoints', models.IntegerField()),
                ('region', models.CharField(max_length=10)),
            ],
        ),
    ]
