# Generated by Django 4.1 on 2022-08-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_ladder_player_rename_challenge_ladder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='absolute_lp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='platform',
            field=models.CharField(choices=[('euw1', 'EUW'), ('na1', 'NA'), ('br1', 'BR'), ('eun1', 'EUNE'), ('jp1', 'JP'), ('kr', 'KR'), ('la1', 'LAN'), ('la2', 'LAS'), ('oc1', 'OCE'), ('ru', 'RU'), ('tr1', 'TR')], default='euw1', max_length=10),
        ),
    ]
