# Generated by Django 3.2 on 2021-07-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_trackedplayers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='leaguedata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='trackedplayers',
            name='id',
        ),
        migrations.AlterField(
            model_name='leaguedata',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trackedplayers',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
