# Generated by Django 3.2 on 2021-07-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20210716_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguedata',
            name='progressDelta',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
