# Generated by Django 3.2 on 2021-07-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_leaguedata_progressdelta'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='queueType',
            field=models.CharField(default='RANKED_SOLO_5x5', max_length=25),
            preserve_default=False,
        ),
    ]
