# Generated by Django 3.2 on 2021-07-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_challenge_queuetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedplayers',
            name='ignored',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
