# Generated by Django 3.2 on 2021-07-17 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_challenge_queuetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='queueType',
        ),
    ]
