# Generated by Django 3.2 on 2021-07-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_trackedplayers_ignored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='queueType',
            field=models.CharField(choices=[('SoloQ', 'RANKED_SOLO_5x5'), ('Flex', 'RANKED_FLEX_5x5')], default='RANKED_SOLO_5x5', max_length=25),
        ),
        migrations.AlterField(
            model_name='trackedplayers',
            name='ignored',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trackedplayers',
            name='region',
            field=models.CharField(choices=[('EUW', 'EUW1'), ('BR', 'BR1'), ('EUNE', 'EUN1'), ('JP', 'JP1'), ('KR', 'KR1'), ('LAN', 'LA1'), ('LAS', 'LA2'), ('OCE', 'OC1'), ('RU', 'RU'), ('TR', 'TR1')], default='EUW', max_length=10),
        ),
        migrations.AlterField(
            model_name='trackedplayers',
            name='startingRank',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], default='I', max_length=10),
        ),
        migrations.AlterField(
            model_name='trackedplayers',
            name='startingTier',
            field=models.CharField(choices=[('IRON', 'IRON'), ('BRONZE', 'BRONZE'), ('SILVER', 'SILVER'), ('GOLD', 'GOLD'), ('PLATINUM', 'PLATINUM'), ('DIAMOND', 'DIAMOND')], default='SILVER', max_length=30),
        ),
    ]
