# Generated by Django 3.2 on 2021-07-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_auto_20210722_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='lastUpdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
