# Generated by Django 3.2 on 2021-07-21 22:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_alter_challenge_lastupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='lastUpdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
