# Generated by Django 3.2 on 2021-07-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_auto_20210722_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='queueType',
            field=models.CharField(choices=[('RANKED_SOLO_5x5', 'RANKED_SOLO_5x5'), ('RANKED_FLEX_SR', 'RANKED_SR_5x5')], default='RANKED_SOLO_5x5', max_length=25),
        ),
        migrations.AlterField(
            model_name='trackedplayers',
            name='region',
            field=models.CharField(choices=[('EUW1', 'EUW1'), ('BR1', 'BR1'), ('EUN1', 'EUN1'), ('JP1', 'JP1'), ('KR1', 'KR1'), ('LA1', 'LA1'), ('LA2', 'LA2'), ('OC1', 'OC1'), ('RU', 'RU'), ('TR1', 'TR1')], default='EUW', max_length=10),
        ),
    ]
