# Generated by Django 3.2 on 2021-07-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_auto_20210722_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguedata',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaguedata',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaguedata',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaguedata',
            name='progressDelta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaguedata',
            name='rank',
            field=models.CharField(default='IV', max_length=100),
        ),
        migrations.AlterField(
            model_name='leaguedata',
            name='tier',
            field=models.CharField(default='IRON', max_length=100),
        ),
        migrations.AlterField(
            model_name='leaguedata',
            name='winrate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='leaguedata',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
