# Generated by Django 3.2 on 2021-08-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_auto_20210811_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedplayers',
            name='accountId',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trackedplayers',
            name='id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
