# Generated by Django 3.2 on 2022-01-02 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_auto_20210811_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguedata',
            name='tracked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.trackedplayers'),
        ),
    ]
